// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Prisma CLI work (migrations, introspection, studio) must go over a DIRECT
// connection. Neon's pooled endpoint (-pooler host, exposed as DATABASE_URL for
// the app runtime) breaks migrations. Fall back to DATABASE_URL for local
// non-Neon setups that only define the one variable.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
